// Auto-generated from Bareback_Rider_10_Week_Program_Varied_v1.xlsx
// 10-week bareback rider program — Pascal Isabelle / ProGrip JP

export type Exercise = {
  name: string;
  setsReps?: string;
};

export type DayPlan = {
  day: number;            // 1-7 (Mon=1, Sun=7)
  dayName: string;
  focus: string;
  exercises: Exercise[];
  rest?: string;
  conditioning?: string;
  notes?: string;
  isRestDay?: boolean;
};

export type WeekPlan = {
  weekNumber: number;
  title: string;
  days: DayPlan[];
};

export const TEN_WEEK_PLAN: WeekPlan[] = [
  {
    weekNumber: 1,
    title: 'Body Position and Balance',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Lower Body Power & Hip Drive',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Box Jumps', setsReps: '5x3' },
          { name: 'Back Squat', setsReps: '4x6 @75–80%' },
          { name: 'Hanging Leg Raise', setsReps: '3x12' },
          { name: 'Hip Flexor + Couch Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Run 1.5 miles steady',
        notes: 'Drive through heels on squats, explode off the box, and keep the chest tall on the spur board. Week 1 emphasis: hold bareback body position throughout — chin up, chest open, toes turned out.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Upper Body Push & Anti-Rotation Core',
        exercises: [
          { name: 'Banded Shoulder Warm-Up' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Push Press', setsReps: '4x5' },
          { name: 'DB Bench Press', setsReps: '3x8' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Plank Pull-Through', setsReps: '3x20' },
          { name: 'Pec/Lat Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 25 minutes Zone 2',
        notes: 'Lock out fully overhead, resist trunk rotation on the Pallof, and breathe out on lockout. Week 1 emphasis: hold bareback body position throughout — chin up, chest open, toes turned out.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Strength & Posterior Chain Power',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Kettlebell Swing' },
          { name: 'Romanian Deadlift' },
          { name: 'Weighted Chin-Up', setsReps: '4x5' },
          { name: 'Farmer Carry', setsReps: '3x40 yd' },
          { name: 'Hamstring/Glute Stretch' },
        ],
        rest: '75–120 sec',
        conditioning: 'Row 12 min — alternate 1 min hard / 1 min easy',
        notes: 'Hinge from the hips, squeeze glutes hard at the top of the swing, and crush the bar on chin-ups. Week 1 emphasis: hold bareback body position throughout — chin up, chest open, toes turned out.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Unilateral Strength & Balance',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Bulgarian Split Squat', setsReps: '3x8/leg' },
          { name: 'Single-Leg RDL', setsReps: '3x6/leg' },
          { name: 'Step-Up to Knee Drive', setsReps: '3x6/leg' },
          { name: 'Side Plank', setsReps: '3x30s/side' },
          { name: 'Adductor Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Incline treadmill or hill walk 20 min',
        notes: 'Stay tall with the knee tracking over the toe, control the descent, and brace as if holding position in the chute. Week 1 emphasis: hold bareback body position throughout — chin up, chest open, toes turned out.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip, Forearm & Riding-Arm Endurance',
        exercises: [
          { name: 'Wrist/Forearm Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Dead Hang', setsReps: '3x max' },
          { name: 'Towel Pull-Up', setsReps: '3x6' },
          { name: 'Bent-Over Row', setsReps: '4x8' },
          { name: 'Plate Pinch Hold', setsReps: '3x30s' },
          { name: 'Wrist Curl', setsReps: '3x12' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 20 min easy spin',
        notes: 'Active shoulders on the hang, pinch the plates like a rigging handle, and keep elbows tight on rows. Week 1 emphasis: hold bareback body position throughout — chin up, chest open, toes turned out.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Power & Sport-Specific Carryover',
        exercises: [
          { name: 'Movement Prep' },
          { name: 'Spur Board (extended)', setsReps: '4x10' },
          { name: 'Power Clean', setsReps: '5x3' },
          { name: 'Med Ball Slam', setsReps: '4x5' },
          { name: 'DB Snatch', setsReps: '3x5/side' },
          { name: 'Dead Bug', setsReps: '3x10/side' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: '90–120 sec on lifts',
        conditioning: 'Row 10 min sprint intervals — 30s on / 30s off',
        notes: 'Aggressive hip extension, finish tall on cleans, and mimic the bareback rhythm on the spur board — chin up, toes out. Week 1 emphasis: hold bareback body position throughout — chin up, chest open, toes turned out.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 2,
    title: 'Hip Mobility and Pelvic Control',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Lower Body Power & Hip Drive',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Box Jumps', setsReps: '5x3' },
          { name: 'Back Squat', setsReps: '4x6 @75–80%' },
          { name: 'Hanging Leg Raise', setsReps: '3x12' },
          { name: 'Hip Flexor + Couch Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Run 1.5 miles steady',
        notes: 'Drive through heels on squats, explode off the box, and keep the chest tall on the spur board. Week 2 emphasis: add 5 min of dedicated hip openers (90/90, pigeon, frog) before each session.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Upper Body Push & Anti-Rotation Core',
        exercises: [
          { name: 'Banded Shoulder Warm-Up' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Push Press', setsReps: '4x5' },
          { name: 'DB Bench Press', setsReps: '3x8' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Plank Pull-Through', setsReps: '3x20' },
          { name: 'Pec/Lat Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 25 minutes Zone 2',
        notes: 'Lock out fully overhead, resist trunk rotation on the Pallof, and breathe out on lockout. Week 2 emphasis: add 5 min of dedicated hip openers (90/90, pigeon, frog) before each session.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Strength & Posterior Chain Power',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Kettlebell Swing' },
          { name: 'Romanian Deadlift' },
          { name: 'Weighted Chin-Up', setsReps: '4x5' },
          { name: 'Farmer Carry', setsReps: '3x40 yd' },
          { name: 'Hamstring/Glute Stretch' },
        ],
        rest: '75–120 sec',
        conditioning: 'Row 12 min — alternate 1 min hard / 1 min easy',
        notes: 'Hinge from the hips, squeeze glutes hard at the top of the swing, and crush the bar on chin-ups. Week 2 emphasis: add 5 min of dedicated hip openers (90/90, pigeon, frog) before each session.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Unilateral Strength & Balance',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Bulgarian Split Squat', setsReps: '3x8/leg' },
          { name: 'Single-Leg RDL', setsReps: '3x6/leg' },
          { name: 'Step-Up to Knee Drive', setsReps: '3x6/leg' },
          { name: 'Side Plank', setsReps: '3x30s/side' },
          { name: 'Adductor Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Incline treadmill or hill walk 20 min',
        notes: 'Stay tall with the knee tracking over the toe, control the descent, and brace as if holding position in the chute. Week 2 emphasis: add 5 min of dedicated hip openers (90/90, pigeon, frog) before each session.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip, Forearm & Riding-Arm Endurance',
        exercises: [
          { name: 'Wrist/Forearm Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Dead Hang', setsReps: '3x max' },
          { name: 'Towel Pull-Up', setsReps: '3x6' },
          { name: 'Bent-Over Row', setsReps: '4x8' },
          { name: 'Plate Pinch Hold', setsReps: '3x30s' },
          { name: 'Wrist Curl', setsReps: '3x12' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 20 min easy spin',
        notes: 'Active shoulders on the hang, pinch the plates like a rigging handle, and keep elbows tight on rows. Week 2 emphasis: add 5 min of dedicated hip openers (90/90, pigeon, frog) before each session.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Power & Sport-Specific Carryover',
        exercises: [
          { name: 'Movement Prep' },
          { name: 'Spur Board (extended)', setsReps: '4x10' },
          { name: 'Power Clean', setsReps: '5x3' },
          { name: 'Med Ball Slam', setsReps: '4x5' },
          { name: 'DB Snatch', setsReps: '3x5/side' },
          { name: 'Dead Bug', setsReps: '3x10/side' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: '90–120 sec on lifts',
        conditioning: 'Row 10 min sprint intervals — 30s on / 30s off',
        notes: 'Aggressive hip extension, finish tall on cleans, and mimic the bareback rhythm on the spur board — chin up, toes out. Week 2 emphasis: add 5 min of dedicated hip openers (90/90, pigeon, frog) before each session.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 3,
    title: 'Foot Position and Lower Body Connection',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Lower Body Power & Hip Drive',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Box Jumps', setsReps: '5x3' },
          { name: 'Back Squat', setsReps: '4x6 @75–80%' },
          { name: 'Hanging Leg Raise', setsReps: '3x12' },
          { name: 'Hip Flexor + Couch Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Run 1.5 miles steady',
        notes: 'Drive through heels on squats, explode off the box, and keep the chest tall on the spur board. Week 3 emphasis: keep toes turned out and feet driving forward on every spur board set.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Upper Body Push & Anti-Rotation Core',
        exercises: [
          { name: 'Banded Shoulder Warm-Up' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Push Press', setsReps: '4x5' },
          { name: 'DB Bench Press', setsReps: '3x8' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Plank Pull-Through', setsReps: '3x20' },
          { name: 'Pec/Lat Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 25 minutes Zone 2',
        notes: 'Lock out fully overhead, resist trunk rotation on the Pallof, and breathe out on lockout. Week 3 emphasis: keep toes turned out and feet driving forward on every spur board set.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Strength & Posterior Chain Power',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Kettlebell Swing' },
          { name: 'Romanian Deadlift' },
          { name: 'Weighted Chin-Up', setsReps: '4x5' },
          { name: 'Farmer Carry', setsReps: '3x40 yd' },
          { name: 'Hamstring/Glute Stretch' },
        ],
        rest: '75–120 sec',
        conditioning: 'Row 12 min — alternate 1 min hard / 1 min easy',
        notes: 'Hinge from the hips, squeeze glutes hard at the top of the swing, and crush the bar on chin-ups. Week 3 emphasis: keep toes turned out and feet driving forward on every spur board set.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Unilateral Strength & Balance',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Bulgarian Split Squat', setsReps: '3x8/leg' },
          { name: 'Single-Leg RDL', setsReps: '3x6/leg' },
          { name: 'Step-Up to Knee Drive', setsReps: '3x6/leg' },
          { name: 'Side Plank', setsReps: '3x30s/side' },
          { name: 'Adductor Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Incline treadmill or hill walk 20 min',
        notes: 'Stay tall with the knee tracking over the toe, control the descent, and brace as if holding position in the chute. Week 3 emphasis: keep toes turned out and feet driving forward on every spur board set.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip, Forearm & Riding-Arm Endurance',
        exercises: [
          { name: 'Wrist/Forearm Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Dead Hang', setsReps: '3x max' },
          { name: 'Towel Pull-Up', setsReps: '3x6' },
          { name: 'Bent-Over Row', setsReps: '4x8' },
          { name: 'Plate Pinch Hold', setsReps: '3x30s' },
          { name: 'Wrist Curl', setsReps: '3x12' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 20 min easy spin',
        notes: 'Active shoulders on the hang, pinch the plates like a rigging handle, and keep elbows tight on rows. Week 3 emphasis: keep toes turned out and feet driving forward on every spur board set.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Power & Sport-Specific Carryover',
        exercises: [
          { name: 'Movement Prep' },
          { name: 'Spur Board (extended)', setsReps: '4x10' },
          { name: 'Power Clean', setsReps: '5x3' },
          { name: 'Med Ball Slam', setsReps: '4x5' },
          { name: 'DB Snatch', setsReps: '3x5/side' },
          { name: 'Dead Bug', setsReps: '3x10/side' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: '90–120 sec on lifts',
        conditioning: 'Row 10 min sprint intervals — 30s on / 30s off',
        notes: 'Aggressive hip extension, finish tall on cleans, and mimic the bareback rhythm on the spur board — chin up, toes out. Week 3 emphasis: keep toes turned out and feet driving forward on every spur board set.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 4,
    title: 'Recovery and Movement Reset',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Active Recovery & Lower Body Mobility',
        exercises: [
          { name: 'Foam Roll Full Body' },
          { name: 'Spur Board (light)', setsReps: '2x8' },
          { name: 'Goblet Squat', setsReps: '3x10 light' },
          { name: 'World\'s Greatest Stretch' },
          { name: '90/90 Hip Switches', setsReps: '3x8/side' },
          { name: 'Glute Bridge', setsReps: '3x12' },
          { name: 'Diaphragmatic Breathing' },
        ],
        rest: '45–60 sec',
        conditioning: 'Easy walk 25–30 min',
        notes: 'Move slow and intentional. Reset breathing and let the hips open up — this is restoration, not a workout.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Thoracic & Shoulder Reset',
        exercises: [
          { name: 'Cat-Cow' },
          { name: 'Thread the Needle' },
          { name: 'Spur Board (light)', setsReps: '2x8' },
          { name: 'Banded Pull-Apart', setsReps: '3x15' },
          { name: 'Wall Slides', setsReps: '3x10' },
          { name: 'Y-T-W Raises', setsReps: '3x8 each' },
          { name: 'Pec Doorway Stretch' },
        ],
        rest: '45 sec',
        conditioning: 'Bike 15 min easy spin',
        notes: 'Open the chest and pull the shoulder blades down and back. Quality of movement over load.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Posterior Chain Mobility',
        exercises: [
          { name: 'Hip Flow' },
          { name: 'Spur Board (light)', setsReps: '2x10' },
          { name: 'Light KB Deadlift', setsReps: '3x8 light' },
          { name: 'Hamstring Floss' },
          { name: 'Bird Dog', setsReps: '3x8/side' },
          { name: 'Pigeon Stretch', setsReps: '2x60s/side' },
          { name: 'Couch Stretch' },
        ],
        rest: '45–60 sec',
        conditioning: 'Row 10 min easy steady-state',
        notes: 'Loosen up the chain from heel to head. Keep loads light — no grinding reps this week.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Single-Leg Control & Ankle Mobility',
        exercises: [
          { name: 'Ankle CARs' },
          { name: 'Spur Board (light)', setsReps: '2x8' },
          { name: 'Reverse Lunge (BW)', setsReps: '3x8/leg' },
          { name: 'Single-Leg Stance Hold' },
          { name: 'Calf Raise', setsReps: '3x12' },
          { name: 'Half-Kneeling Hip Flexor Stretch' },
        ],
        rest: '45–60 sec',
        conditioning: 'Easy walk 20 min',
        notes: 'Find the small balance corrections — let the foot and ankle do the work without over-gripping.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip & Forearm Recovery',
        exercises: [
          { name: 'Wrist/Forearm Mobility' },
          { name: 'Spur Board (light)', setsReps: '2x10' },
          { name: 'Light Dead Hang', setsReps: '3x20s' },
          { name: 'Band Wrist Curls', setsReps: '3x12' },
          { name: 'Towel Squeezes', setsReps: '3x20s' },
          { name: 'Forearm Massage Roll' },
        ],
        rest: '45 sec',
        conditioning: 'Bike 15 min easy',
        notes: 'Decompress the grip. Hangs are passive — let the joints breathe.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Flow & Breath Work',
        exercises: [
          { name: 'Yoga Flow (20 min)', setsReps: '20 min' },
          { name: 'Spur Board (light)', setsReps: '2x10' },
          { name: 'Dead Bug', setsReps: '3x8/side' },
          { name: 'Box Breathing', setsReps: '5 min' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: 'As needed',
        conditioning: 'Optional easy walk 15–20 min',
        notes: 'End the week feeling lighter than you started. Keep the nervous system calm.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 5,
    title: 'Shoulder Stability and Grip Control',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Lower Body Power & Hip Drive',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Box Jumps', setsReps: '5x3' },
          { name: 'Back Squat', setsReps: '4x6 @75–80%' },
          { name: 'Hanging Leg Raise', setsReps: '3x12' },
          { name: 'Hip Flexor + Couch Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Run 1.5 miles steady',
        notes: 'Drive through heels on squats, explode off the box, and keep the chest tall on the spur board. Week 5 emphasis: pause 1 sec at the top of every pull and lock the shoulder blade down.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Upper Body Push & Anti-Rotation Core',
        exercises: [
          { name: 'Banded Shoulder Warm-Up' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Push Press', setsReps: '4x5' },
          { name: 'DB Bench Press', setsReps: '3x8' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Plank Pull-Through', setsReps: '3x20' },
          { name: 'Pec/Lat Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 25 minutes Zone 2',
        notes: 'Lock out fully overhead, resist trunk rotation on the Pallof, and breathe out on lockout. Week 5 emphasis: pause 1 sec at the top of every pull and lock the shoulder blade down.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Strength & Posterior Chain Power',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Kettlebell Swing' },
          { name: 'Romanian Deadlift' },
          { name: 'Weighted Chin-Up', setsReps: '4x5' },
          { name: 'Farmer Carry', setsReps: '3x40 yd' },
          { name: 'Hamstring/Glute Stretch' },
        ],
        rest: '75–120 sec',
        conditioning: 'Row 12 min — alternate 1 min hard / 1 min easy',
        notes: 'Hinge from the hips, squeeze glutes hard at the top of the swing, and crush the bar on chin-ups. Week 5 emphasis: pause 1 sec at the top of every pull and lock the shoulder blade down.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Unilateral Strength & Balance',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Bulgarian Split Squat', setsReps: '3x8/leg' },
          { name: 'Single-Leg RDL', setsReps: '3x6/leg' },
          { name: 'Step-Up to Knee Drive', setsReps: '3x6/leg' },
          { name: 'Side Plank', setsReps: '3x30s/side' },
          { name: 'Adductor Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Incline treadmill or hill walk 20 min',
        notes: 'Stay tall with the knee tracking over the toe, control the descent, and brace as if holding position in the chute. Week 5 emphasis: pause 1 sec at the top of every pull and lock the shoulder blade down.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip, Forearm & Riding-Arm Endurance',
        exercises: [
          { name: 'Wrist/Forearm Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Dead Hang', setsReps: '3x max' },
          { name: 'Towel Pull-Up', setsReps: '3x6' },
          { name: 'Bent-Over Row', setsReps: '4x8' },
          { name: 'Plate Pinch Hold', setsReps: '3x30s' },
          { name: 'Wrist Curl', setsReps: '3x12' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 20 min easy spin',
        notes: 'Active shoulders on the hang, pinch the plates like a rigging handle, and keep elbows tight on rows. Week 5 emphasis: pause 1 sec at the top of every pull and lock the shoulder blade down.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Power & Sport-Specific Carryover',
        exercises: [
          { name: 'Movement Prep' },
          { name: 'Spur Board (extended)', setsReps: '4x10' },
          { name: 'Power Clean', setsReps: '5x3' },
          { name: 'Med Ball Slam', setsReps: '4x5' },
          { name: 'DB Snatch', setsReps: '3x5/side' },
          { name: 'Dead Bug', setsReps: '3x10/side' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: '90–120 sec on lifts',
        conditioning: 'Row 10 min sprint intervals — 30s on / 30s off',
        notes: 'Aggressive hip extension, finish tall on cleans, and mimic the bareback rhythm on the spur board — chin up, toes out. Week 5 emphasis: pause 1 sec at the top of every pull and lock the shoulder blade down.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 6,
    title: 'Mark-Out Mechanics',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Lower Body Power & Hip Drive',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Box Jumps', setsReps: '5x3' },
          { name: 'Back Squat', setsReps: '4x6 @75–80%' },
          { name: 'Hanging Leg Raise', setsReps: '3x12' },
          { name: 'Hip Flexor + Couch Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Run 1.5 miles steady',
        notes: 'Drive through heels on squats, explode off the box, and keep the chest tall on the spur board. Week 6 emphasis: include 3 mark-out simulations on the spur board each day — chin up, toes out, hold 8 sec.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Upper Body Push & Anti-Rotation Core',
        exercises: [
          { name: 'Banded Shoulder Warm-Up' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Push Press', setsReps: '4x5' },
          { name: 'DB Bench Press', setsReps: '3x8' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Plank Pull-Through', setsReps: '3x20' },
          { name: 'Pec/Lat Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 25 minutes Zone 2',
        notes: 'Lock out fully overhead, resist trunk rotation on the Pallof, and breathe out on lockout. Week 6 emphasis: include 3 mark-out simulations on the spur board each day — chin up, toes out, hold 8 sec.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Strength & Posterior Chain Power',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Kettlebell Swing' },
          { name: 'Romanian Deadlift' },
          { name: 'Weighted Chin-Up', setsReps: '4x5' },
          { name: 'Farmer Carry', setsReps: '3x40 yd' },
          { name: 'Hamstring/Glute Stretch' },
        ],
        rest: '75–120 sec',
        conditioning: 'Row 12 min — alternate 1 min hard / 1 min easy',
        notes: 'Hinge from the hips, squeeze glutes hard at the top of the swing, and crush the bar on chin-ups. Week 6 emphasis: include 3 mark-out simulations on the spur board each day — chin up, toes out, hold 8 sec.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Unilateral Strength & Balance',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Bulgarian Split Squat', setsReps: '3x8/leg' },
          { name: 'Single-Leg RDL', setsReps: '3x6/leg' },
          { name: 'Step-Up to Knee Drive', setsReps: '3x6/leg' },
          { name: 'Side Plank', setsReps: '3x30s/side' },
          { name: 'Adductor Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Incline treadmill or hill walk 20 min',
        notes: 'Stay tall with the knee tracking over the toe, control the descent, and brace as if holding position in the chute. Week 6 emphasis: include 3 mark-out simulations on the spur board each day — chin up, toes out, hold 8 sec.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip, Forearm & Riding-Arm Endurance',
        exercises: [
          { name: 'Wrist/Forearm Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Dead Hang', setsReps: '3x max' },
          { name: 'Towel Pull-Up', setsReps: '3x6' },
          { name: 'Bent-Over Row', setsReps: '4x8' },
          { name: 'Plate Pinch Hold', setsReps: '3x30s' },
          { name: 'Wrist Curl', setsReps: '3x12' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 20 min easy spin',
        notes: 'Active shoulders on the hang, pinch the plates like a rigging handle, and keep elbows tight on rows. Week 6 emphasis: include 3 mark-out simulations on the spur board each day — chin up, toes out, hold 8 sec.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Power & Sport-Specific Carryover',
        exercises: [
          { name: 'Movement Prep' },
          { name: 'Spur Board (extended)', setsReps: '4x10' },
          { name: 'Power Clean', setsReps: '5x3' },
          { name: 'Med Ball Slam', setsReps: '4x5' },
          { name: 'DB Snatch', setsReps: '3x5/side' },
          { name: 'Dead Bug', setsReps: '3x10/side' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: '90–120 sec on lifts',
        conditioning: 'Row 10 min sprint intervals — 30s on / 30s off',
        notes: 'Aggressive hip extension, finish tall on cleans, and mimic the bareback rhythm on the spur board — chin up, toes out. Week 6 emphasis: include 3 mark-out simulations on the spur board each day — chin up, toes out, hold 8 sec.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 7,
    title: 'Recovery and Re-Centering',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Active Recovery & Lower Body Mobility',
        exercises: [
          { name: 'Foam Roll Full Body' },
          { name: 'Spur Board (light)', setsReps: '2x8' },
          { name: 'Goblet Squat', setsReps: '3x10 light' },
          { name: 'World\'s Greatest Stretch' },
          { name: '90/90 Hip Switches', setsReps: '3x8/side' },
          { name: 'Glute Bridge', setsReps: '3x12' },
          { name: 'Diaphragmatic Breathing' },
        ],
        rest: '45–60 sec',
        conditioning: 'Easy walk 25–30 min',
        notes: 'Move slow and intentional. Reset breathing and let the hips open up — this is restoration, not a workout.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Thoracic & Shoulder Reset',
        exercises: [
          { name: 'Cat-Cow' },
          { name: 'Thread the Needle' },
          { name: 'Spur Board (light)', setsReps: '2x8' },
          { name: 'Banded Pull-Apart', setsReps: '3x15' },
          { name: 'Wall Slides', setsReps: '3x10' },
          { name: 'Y-T-W Raises', setsReps: '3x8 each' },
          { name: 'Pec Doorway Stretch' },
        ],
        rest: '45 sec',
        conditioning: 'Bike 15 min easy spin',
        notes: 'Open the chest and pull the shoulder blades down and back. Quality of movement over load.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Posterior Chain Mobility',
        exercises: [
          { name: 'Hip Flow' },
          { name: 'Spur Board (light)', setsReps: '2x10' },
          { name: 'Light KB Deadlift', setsReps: '3x8 light' },
          { name: 'Hamstring Floss' },
          { name: 'Bird Dog', setsReps: '3x8/side' },
          { name: 'Pigeon Stretch', setsReps: '2x60s/side' },
          { name: 'Couch Stretch' },
        ],
        rest: '45–60 sec',
        conditioning: 'Row 10 min easy steady-state',
        notes: 'Loosen up the chain from heel to head. Keep loads light — no grinding reps this week.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Single-Leg Control & Ankle Mobility',
        exercises: [
          { name: 'Ankle CARs' },
          { name: 'Spur Board (light)', setsReps: '2x8' },
          { name: 'Reverse Lunge (BW)', setsReps: '3x8/leg' },
          { name: 'Single-Leg Stance Hold' },
          { name: 'Calf Raise', setsReps: '3x12' },
          { name: 'Half-Kneeling Hip Flexor Stretch' },
        ],
        rest: '45–60 sec',
        conditioning: 'Easy walk 20 min',
        notes: 'Find the small balance corrections — let the foot and ankle do the work without over-gripping.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip & Forearm Recovery',
        exercises: [
          { name: 'Wrist/Forearm Mobility' },
          { name: 'Spur Board (light)', setsReps: '2x10' },
          { name: 'Light Dead Hang', setsReps: '3x20s' },
          { name: 'Band Wrist Curls', setsReps: '3x12' },
          { name: 'Towel Squeezes', setsReps: '3x20s' },
          { name: 'Forearm Massage Roll' },
        ],
        rest: '45 sec',
        conditioning: 'Bike 15 min easy',
        notes: 'Decompress the grip. Hangs are passive — let the joints breathe.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Flow & Breath Work',
        exercises: [
          { name: 'Yoga Flow (20 min)', setsReps: '20 min' },
          { name: 'Spur Board (light)', setsReps: '2x10' },
          { name: 'Dead Bug', setsReps: '3x8/side' },
          { name: 'Box Breathing', setsReps: '5 min' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: 'As needed',
        conditioning: 'Optional easy walk 15–20 min',
        notes: 'End the week feeling lighter than you started. Keep the nervous system calm.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 8,
    title: 'Speed and Foot Reaction',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Lower Body Power & Hip Drive',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Box Jumps', setsReps: '5x3' },
          { name: 'Back Squat', setsReps: '4x6 @75–80%' },
          { name: 'Hanging Leg Raise', setsReps: '3x12' },
          { name: 'Hip Flexor + Couch Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Run 1.5 miles steady',
        notes: 'Drive through heels on squats, explode off the box, and keep the chest tall on the spur board. Week 8 emphasis: prioritize speed of the first rep — explosive intent over total volume.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Upper Body Push & Anti-Rotation Core',
        exercises: [
          { name: 'Banded Shoulder Warm-Up' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Push Press', setsReps: '4x5' },
          { name: 'DB Bench Press', setsReps: '3x8' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Plank Pull-Through', setsReps: '3x20' },
          { name: 'Pec/Lat Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 25 minutes Zone 2',
        notes: 'Lock out fully overhead, resist trunk rotation on the Pallof, and breathe out on lockout. Week 8 emphasis: prioritize speed of the first rep — explosive intent over total volume.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Strength & Posterior Chain Power',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Kettlebell Swing' },
          { name: 'Romanian Deadlift' },
          { name: 'Weighted Chin-Up', setsReps: '4x5' },
          { name: 'Farmer Carry', setsReps: '3x40 yd' },
          { name: 'Hamstring/Glute Stretch' },
        ],
        rest: '75–120 sec',
        conditioning: 'Row 12 min — alternate 1 min hard / 1 min easy',
        notes: 'Hinge from the hips, squeeze glutes hard at the top of the swing, and crush the bar on chin-ups. Week 8 emphasis: prioritize speed of the first rep — explosive intent over total volume.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Unilateral Strength & Balance',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Bulgarian Split Squat', setsReps: '3x8/leg' },
          { name: 'Single-Leg RDL', setsReps: '3x6/leg' },
          { name: 'Step-Up to Knee Drive', setsReps: '3x6/leg' },
          { name: 'Side Plank', setsReps: '3x30s/side' },
          { name: 'Adductor Stretch' },
        ],
        rest: '60–90 sec',
        conditioning: 'Incline treadmill or hill walk 20 min',
        notes: 'Stay tall with the knee tracking over the toe, control the descent, and brace as if holding position in the chute. Week 8 emphasis: prioritize speed of the first rep — explosive intent over total volume.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip, Forearm & Riding-Arm Endurance',
        exercises: [
          { name: 'Wrist/Forearm Warm-Up' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Dead Hang', setsReps: '3x max' },
          { name: 'Towel Pull-Up', setsReps: '3x6' },
          { name: 'Bent-Over Row', setsReps: '4x8' },
          { name: 'Plate Pinch Hold', setsReps: '3x30s' },
          { name: 'Wrist Curl', setsReps: '3x12' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 20 min easy spin',
        notes: 'Active shoulders on the hang, pinch the plates like a rigging handle, and keep elbows tight on rows. Week 8 emphasis: prioritize speed of the first rep — explosive intent over total volume.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Full-Body Power & Sport-Specific Carryover',
        exercises: [
          { name: 'Movement Prep' },
          { name: 'Spur Board (extended)', setsReps: '4x10' },
          { name: 'Power Clean', setsReps: '5x3' },
          { name: 'Med Ball Slam', setsReps: '4x5' },
          { name: 'DB Snatch', setsReps: '3x5/side' },
          { name: 'Dead Bug', setsReps: '3x10/side' },
          { name: 'Foam Roll Full Body' },
        ],
        rest: '90–120 sec on lifts',
        conditioning: 'Row 10 min sprint intervals — 30s on / 30s off',
        notes: 'Aggressive hip extension, finish tall on cleans, and mimic the bareback rhythm on the spur board — chin up, toes out. Week 8 emphasis: prioritize speed of the first rep — explosive intent over total volume.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 9,
    title: 'Competition Simulation',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Explosive Lower Body — Peak Power',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board (full sequence)', setsReps: '4x10' },
          { name: 'Trap Bar Jump', setsReps: '4x3' },
          { name: 'Back Squat (heavy doubles)', setsReps: '4x2 @85%' },
          { name: 'Depth Drop to Stick', setsReps: '3x4' },
          { name: 'Hollow Hold', setsReps: '3x30s' },
          { name: 'Hip Mobility' },
        ],
        rest: '120–180 sec on heavy lifts',
        conditioning: 'Run 1 mile — focus on quality',
        notes: 'Treat every rep like a bareback ride: max intent, then full reset. Do not chase fatigue.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Mark-Out Simulation & Reactive Power',
        exercises: [
          { name: 'Mobility Prep' },
          { name: 'Spur Board (timed 8-second sets)', setsReps: '5x8 sec (full effort)' },
          { name: 'Lateral Bound', setsReps: '4x4/side' },
          { name: 'Med Ball Rotational Throw', setsReps: '4x5/side' },
          { name: 'Half-Kneeling Cable Chop', setsReps: '3x10/side' },
          { name: 'Plank-to-Push-Up' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 15 min — 5x30s sprint / 90s easy',
        notes: 'The 8-second clock is the focus today. Match the cadence and intensity of an actual ride.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Power & Riding-Arm Strength',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Power Clean', setsReps: '5x2' },
          { name: 'Weighted Pull-Up', setsReps: '4x4' },
          { name: 'One-Arm DB Row' },
          { name: 'Rope Slam', setsReps: '3x15s' },
          { name: 'Lat Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Row 10 min — 1 min hard / 1 min easy',
        notes: 'Pull aggressively, finish every clean tall, and keep the rigging arm engaged on rows.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Single-Leg Power & Stability Under Load',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Skater Bound', setsReps: '3x4/side' },
          { name: 'Rear-Foot Elevated Split Squat', setsReps: '3x6/leg @load' },
          { name: 'Single-Leg Box Jump', setsReps: '3x4/leg' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Couch Stretch' },
        ],
        rest: '75–90 sec',
        conditioning: 'Hill sprints 6x20 sec, full recovery between',
        notes: 'Land soft, drive hard. Each side independent — no leaning into the strong leg.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip Under Fatigue & Mental Reps',
        exercises: [
          { name: 'Wrist Prep' },
          { name: 'Spur Board (timed)', setsReps: '4x10 (timed 8 sec)' },
          { name: 'Bareback Rigging Hang (if available, else Towel Pull-Up)' },
          { name: 'Plate Pinch Walk', setsReps: '3x40 yd' },
          { name: 'Visualization (5 min)' },
          { name: 'Forearm Roll' },
        ],
        rest: '90 sec',
        conditioning: 'Bike 15 min easy + 5 min visualization',
        notes: 'Hold past comfortable. Run mental reps of a full ride — chute to whistle — between sets.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Ride-Day Simulation',
        exercises: [
          { name: 'Full Warm-Up Routine (as on ride day)' },
          { name: 'Spur Board 8-Second Drill', setsReps: '6x8 sec @full effort with 90 sec rest' },
          { name: 'Power Clean (light, fast)', setsReps: '4x3 light & fast' },
          { name: 'Med Ball Slam', setsReps: '3x5' },
          { name: 'Cool-Down Walk' },
          { name: 'Foam Roll' },
        ],
        rest: '90 sec between rounds',
        conditioning: 'Easy walk + breath work 15 min',
        notes: 'Rehearse the whole ride-day flow: warm-up, focus, execute, reset. Build the routine you will use at competition.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
  {
    weekNumber: 10,
    title: 'Rider Identity and Flow State',
    days: [
      {
        day: 1,
        dayName: 'Monday',
        focus: 'Explosive Lower Body — Peak Power',
        exercises: [
          { name: 'Dynamic Warm-Up' },
          { name: 'Spur Board (full sequence)', setsReps: '4x10' },
          { name: 'Trap Bar Jump', setsReps: '4x3' },
          { name: 'Back Squat (heavy doubles)', setsReps: '4x2 @85%' },
          { name: 'Depth Drop to Stick', setsReps: '3x4' },
          { name: 'Hollow Hold', setsReps: '3x30s' },
          { name: 'Hip Mobility' },
        ],
        rest: '120–180 sec on heavy lifts',
        conditioning: 'Run 1 mile — focus on quality',
        notes: 'Treat every rep like a bareback ride: max intent, then full reset. Do not chase fatigue.',
      },
      {
        day: 2,
        dayName: 'Tuesday',
        focus: 'Mark-Out Simulation & Reactive Power',
        exercises: [
          { name: 'Mobility Prep' },
          { name: 'Spur Board (timed 8-second sets)', setsReps: '5x8 sec (full effort)' },
          { name: 'Lateral Bound', setsReps: '4x4/side' },
          { name: 'Med Ball Rotational Throw', setsReps: '4x5/side' },
          { name: 'Half-Kneeling Cable Chop', setsReps: '3x10/side' },
          { name: 'Plank-to-Push-Up' },
        ],
        rest: '60–90 sec',
        conditioning: 'Bike 15 min — 5x30s sprint / 90s easy',
        notes: 'The 8-second clock is the focus today. Match the cadence and intensity of an actual ride.',
      },
      {
        day: 3,
        dayName: 'Wednesday',
        focus: 'Pulling Power & Riding-Arm Strength',
        exercises: [
          { name: 'Hip Mobility Flow' },
          { name: 'Spur Board', setsReps: '3x10' },
          { name: 'Power Clean', setsReps: '5x2' },
          { name: 'Weighted Pull-Up', setsReps: '4x4' },
          { name: 'One-Arm DB Row' },
          { name: 'Rope Slam', setsReps: '3x15s' },
          { name: 'Lat Stretch' },
        ],
        rest: '90–120 sec',
        conditioning: 'Row 10 min — 1 min hard / 1 min easy',
        notes: 'Pull aggressively, finish every clean tall, and keep the rigging arm engaged on rows.',
      },
      {
        day: 4,
        dayName: 'Thursday',
        focus: 'Single-Leg Power & Stability Under Load',
        exercises: [
          { name: 'Ankle/Hip Prep' },
          { name: 'Spur Board', setsReps: '3x8' },
          { name: 'Skater Bound', setsReps: '3x4/side' },
          { name: 'Rear-Foot Elevated Split Squat', setsReps: '3x6/leg @load' },
          { name: 'Single-Leg Box Jump', setsReps: '3x4/leg' },
          { name: 'Pallof Press', setsReps: '3x10/side' },
          { name: 'Couch Stretch' },
        ],
        rest: '75–90 sec',
        conditioning: 'Hill sprints 6x20 sec, full recovery between',
        notes: 'Land soft, drive hard. Each side independent — no leaning into the strong leg.',
      },
      {
        day: 5,
        dayName: 'Friday',
        focus: 'Grip Under Fatigue & Mental Reps',
        exercises: [
          { name: 'Wrist Prep' },
          { name: 'Spur Board (timed)', setsReps: '4x10 (timed 8 sec)' },
          { name: 'Bareback Rigging Hang (if available, else Towel Pull-Up)' },
          { name: 'Plate Pinch Walk', setsReps: '3x40 yd' },
          { name: 'Visualization (5 min)' },
          { name: 'Forearm Roll' },
        ],
        rest: '90 sec',
        conditioning: 'Bike 15 min easy + 5 min visualization',
        notes: 'Hold past comfortable. Run mental reps of a full ride — chute to whistle — between sets.',
      },
      {
        day: 6,
        dayName: 'Saturday',
        focus: 'Ride-Day Simulation',
        exercises: [
          { name: 'Full Warm-Up Routine (as on ride day)' },
          { name: 'Spur Board 8-Second Drill', setsReps: '6x8 sec @full effort with 90 sec rest' },
          { name: 'Power Clean (light, fast)', setsReps: '4x3 light & fast' },
          { name: 'Med Ball Slam', setsReps: '3x5' },
          { name: 'Cool-Down Walk' },
          { name: 'Foam Roll' },
        ],
        rest: '90 sec between rounds',
        conditioning: 'Easy walk + breath work 15 min',
        notes: 'Rehearse the whole ride-day flow: warm-up, focus, execute, reset. Build the routine you will use at competition.',
      },
      {
        day: 7,
        dayName: 'Sunday',
        focus: 'Rest / Makeup',
        exercises: [],
        notes: 'Use this day to rest, recover, or make up a missed session from earlier in the week.',
        isRestDay: true,
      },
    ],
  },
];

// Helper: get a specific day plan
export function getWorkout(week: number, day: number): DayPlan | null {
  const wk = TEN_WEEK_PLAN.find((w) => w.weekNumber === week);
  if (!wk) return null;
  return wk.days.find((d) => d.day === day) ?? null;
}

// Helper: total number of weeks in the 10-week program
export const TEN_WEEK_TOTAL_WEEKS = TEN_WEEK_PLAN.length;
